# Logging configuration for supply chain environments
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "[%(asctime)s] [%(process)d] [%(levelname)s] [%(name)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S %z"
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: """
    {
        "timestamp": "%(asctime)s",
        "process": "%(process)d",
        "level": "%(levelname)s",
        "logger": "%(name)s",
        "message": "%(message)s",
        "module": "%(module)s",
        "function": "%(funcName)s",
        "line": "%(lineno)d"
    }
    """

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/supplychain.log
    when: midnight
    backupCount: 30
    encoding: utf-8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: logs/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf-8

loggers:
  api:
    handlers: [console, file, error_file]
    level: INFO
    propagate: false
    
  models:
    handlers: [file, error_file]
    level: DEBUG
    propagate: false

  blockchain:
    handlers: [file]
    level: WARNING
    propagate: false

  geospatial:
    handlers: [console, file]
    level: INFO
    propagate: false

root:
  handlers: [console, file]
  level: WARNING
